apiVersion: v1
kind: Service
metadata:
  name: glance-service
spec:
  type: NodePort # Expõe o serviço em uma porta de todos os nós (ideal para homelab)
  selector:
    app: glance # Deve corresponder ao 'label' definido no Deployment
  ports:
    - protocol: TCP
      port: 8080      # Porta interna do Service
      targetPort: 8080  # A porta do container (Glance App)
      nodePort: 30080   # Porta externa no nó (Escolha qualquer uma entre 30000-32767)
